### ISSUE TITLE
node-gyp issues on Windows

### ISSUE THREAD

**Issue by fafnirical** [forumone/generator-web-starter-gesso#11]
[libxmljs](https://github.com/libxmljs/libxmljs) doesn't come with prebuilt binaries (until https://github.com/libxmljs/libxmljs/pull/407 is merged in), so this won't install on Windows unless you can compile the binaries yourself, with Python and Visual Studio.

**Comment by wwhurley** [comment]
We can probably switch to using `jsdom` instead of libxmljs.

**Comment by wwhurley** [comment]
Resolved by changing to use jsdom and wgxpath
