### ISSUE TITLE
Remove patternlab options

### ISSUE THREAD

**Issue by mortona42** [forumone/generator-web-starter-gesso#18]
Currently it's downloading the wrong version.  

Corey says to install manually via composer: https://github.com/pattern-lab/edition-php-twig-standard

**Comment by coreylafferty** [comment]
Currently this is the command that we run to manually install Pattern Lab.

$ composer create-project pattern-lab/edition-drupal-standard pattern-lab

Answers to all the 'merge or replace' questions should be 'replace'.  When prompted for a starterkit, the fourth one should be selected (starterkit-twig-drupal-gesso).  If this can't be done, we can just remove PL from the generator and install PL manually.

**Comment by mortona42** [comment]
Should I also remove gruntPatternlab() from the configuring section?

**Comment by mortona42** [comment]
I'll work on that in #22

**Comment by wwhurley** [comment]
Pattern Lab has been removed as part of 0.2.
