### ISSUE TITLE
Download Gesso theme

### ISSUE THREAD

**Issue by wwhurley** [forumone/generator-web-starter-gesso#2]
Download appropriate Gesso theme for the platform selected. Should prompt the user to install a fresh copy of Gesso to avoid overwriting work.

**Comment by wwhurley** [comment]
@coreylafferty Can you provide the URLs to the appropriate themes for WordPress and Drupal?

**Comment by tla-dev** [comment]
I used this one for Drupal: https://www.drupal.org/project/gesso
