### ISSUE TITLE
Fix grunt in project root

### ISSUE THREAD

**Issue by mortona42** [forumone/generator-web-starter-gesso#23]
We want to run grunt from the project root, including building gesso/sass/pattern-lab stuff.  Jenkins should be configured to run grunt from the root in every project.

Currently to make things work, we have to replace the root tasks directory with the one in Gesso, and copy gesso's package.json dependencies to the root package.json.

#21 and #22 will take a look at how package.json is loading those dependencies into the file.  We'll either update those generator functions to copy actual gesso dependencies, or in this ticket, we can look at just copying the files after they're downloaded.

**Comment by wwhurley** [comment]
For all projects Jenkins does run `grunt` at the root of the workspace. So no changes should be necessary there.

**Comment by mortona42** [comment]
It's broken though.  You need to manually copy the tasks and package.json dependencies to get running.  This ticket is to do that copy as part of the scaffolding, if it can't be fixed via #21 or #22.

**Comment by wwhurley** [comment]
Running `grunt` and `grunt build` in the root of the project will delegate to the appropriate tasks in the theme. Resolved as part of 0.2.
