### ISSUE TITLE
Generator fails to download .gitignore

### ISSUE THREAD

**Issue by mortona42** [forumone/generator-web-starter-gesso#24]
Edit:
After some discussion, we realized the issue is that the existing .gitignore file is not downloaded via yeoman.

After running grunt, these directories are created and not included in gitignore.

        public/themes/gesso/css/
        public/themes/gesso/sass/partials/sass-globbing/

**Comment by mortona42** [comment]
@coreylafferty I'm sure we want to ignore css, but what about the sass-globbing dir?

**Comment by mortona42** [comment]
@wwhurley how can I append to the root .gitignore via this generator?

**Comment by wwhurley** [comment]
Is there a reason why this should be in the root .gitignore instead of one in the theme?

**Comment by mortona42** [comment]
Good question.  I just noticed that the gesso project does have that in a .gitignore.  When downloaded via yeoman, that isn't included.

**Comment by wwhurley** [comment]
So then it's likely an issue with the globbing that copies files from the remote download.

**Comment by mortona42** [comment]
Indeed, it was the globbing.  I added {dot : true} to the options passed to glob().

**Comment by mortona42** [comment]
@coreylafferty Can you test this one too please?
