### ISSUE TITLE
Download Pattern Lab

### ISSUE THREAD

**Issue by wwhurley** [forumone/generator-web-starter-gesso#3]
Download Pattern Lab into appropriate directory in the theme. Should prompt user on whether to install Pattern Lab. Should prompt user on whether to download a new copy of Pattern Lab to avoid overwriting custom work.

**Comment by coreylafferty** [comment]
May also need to modify .gitignore (e.g., to not ignore /source/)

**Comment by tla-dev** [comment]
can you give me the pattern lab theme to use for drupal and wordpress?

**Comment by coreylafferty** [comment]
https://github.com/dcmouyard/patternlab-php-gesso

**Comment by wwhurley** [comment]
So the steps should be:

1. Download Patternlab to a directory in the theme called "pattern-lab"
2. Add `patternlab` target for `copy` task, see https://github.com/forumone/web-starter/blob/1.1.x/tasks/config/copy.js
3. Add `patternlab` target for `shell` task, see https://github.com/forumone/web-starter/blob/1.1.x/tasks/config/shell.js
4. Add `patternlab` target for `watch` task, see https://github.com/forumone/web-starter/blob/1.1.x/tasks/config/watch.js#L11
